### ISSUE TITLE
Implement Graph class

### ISSUE THREAD

**Issue by utilForever** [utilForever/CubbyDNN#18]
We removed Graph-related code in last refactoring process.
Therefore, we want to restore it as class.

**Comment by Ravenwater** [comment]
you can pull me in for code review if you want/need to

**Comment by utilForever** [comment]
@Ravenwater @jwkim98 and me wondering how to implement it.
I am writing a test code first, and [here](https://gist.github.com/utilForever/1e0a93263ff5d52ae35304906e9c980a) is the code my wrote. What do you think?

**Comment by jwkim98** [comment]
@utilForever We need to think about ways to easily pass data to graph, and bring back the results even if they're more than one. Also, we must think about ways to specify loss functions and optimizers for the graph. Are they going to be included in Graph class or not?

Since we're using compile & run method, having Graph class might make it easier to manage multiple graphs, but if there's lots of graph configurations that has to be done from outside, things will get complicated.
