### ISSUE TITLE
Implement activation functions

### ISSUE THREAD

**Issue by jwkim98** [utilForever/CubbyDNN#25]
* Implement activation functions
 Relu, leaky-Relu, logistic, tanh, sigmoid , Linear+ User custom function with its inverse

**Comment by Ravenwater** [comment]
@jwkim98 make certain that the activation functions are parameterized in their data type. Activation functions, due to their non-linear nature are **THE** place in the pipeline where arithmetic/discretization effects manifest, and thus having the ability to play with different number systems will be a key differentiator for doing DNN research.

There is a trick in the TPU that uses a 32-bit accumulator to aggregate the dot-products of INT8 data encoding the weights. This cuts down on saturation/overflow and helps avoiding the need to sort to avoid cancellation. The ability of the pipeline to possibly directly feed these larger accumulators into the activation functions would be helping efficiency and computational fidelity. That is a trickier design pattern to generalize and may require specialized functions as a function of the number system.

**Comment by jwkim98** [comment]
@Ravenwater 
Yes of course. They are going to be able to accept various data types. I'm planning to use templates for this purpose. 
That is the reason why we considered to have template interface from the top-level.

**Comment by Ravenwater** [comment]
To emulate the TPU trick in software, you need two types, the type of the arithmetic and the type of the accumulator. You can set a fixed relationship between the two, but if one stage produces just the accumulator, you would need to be able to adapt. That adaption can be integrated in to the previous stage, or in the current stage. 

So there is a weird/unpleasant design trade-off: you want the interface to be clean and simple, but that limits the flexibility of the type of games you can play. If you support the flexibility, then the interface because unrecognizable for anybody that isn't interested in number systems. 

I would err on the simplicity side, and assume an implicit relationship between these round-off reducing techniques with bigger accumulators. And just pass the arithmetic type. This design forces integration of the adapter at each pipeline output, which will incur a rounding error. But at least that design is consistent with simple GPU float pipelines.

As I said, a difficult trade-off to make.
