### ISSUE TITLE
How do you think about custom matrix&vector type?

### ISSUE THREAD

**Issue by jwkim98** [utilForever/CubbyDNN#32]
We can fix mtl::mat::dense2D as default conversion type from TensorData, but if we are implementing any custom matrix rather than MTL, It might be better to define some custom matrix type and custom functions that can convert custom matrix type into MTL types. 

This is required since data alignment of custom implementation can be different from alignment that MTL is using.
Also, since hpr-blas implementation of non-posit type matrix multiplication requires operators such as * or + , our custom matrix&vector type should support them.

How do you guys think about it? should we fix MTL types as our default matrix type? or should we define our own and add some custom implementations?

**Comment by Ravenwater** [comment]
let me try to catch up with your discovery....

The fundamental 'purpose' of MTL is to abstract away the details of the matrix so that matrix algorithms can be made uniform and independent of the underlying matrix structure. The value of the abstraction is that applications can pick different matrix structures to optimize their performance without having to restructure their codes. Typical examples are progressions from dense to banded to sparse. Or the CSR to CRS and back if you have matrix compositions or transposes.

So, if you have found a matrix structure that isn't supported in MTL, then MTL has failed and we really should think about adding it to MTL.

However, tensors represented by matrices inject 'structure' into the matrix that we do need to take advantage of for efficient execution. Ok, at this point I realize that I need to see an example of your observation that there is a data alignment problem.

**Comment by jwkim98** [comment]
@Ravenwater 
I wonder if there's a way to add custom implementations in operators such as ' +, - , *, /' using MTL.
If we can, There might be no reason to make custom matrix&vector types.
I haven't figured out a way to do so yet.

I proposed custom type to support custom implementations of those operators alongside with MTL.
I thought expressing matrix operations by operators would look simpler rather than passing them as parameters.

I also mentioned about alignment because there can be lots of ways to store multidimensional matrices in sequentially aligned memory space. To make it cache oblivious, data can be stored in different ways.
For example, if we call  C= A*B when C,A,B is MTL matrix types, What kind of data alignment does MTL assume?

If MTL doesn't support custom operators, We can make a wrapper class that contains MTL internally, and implement operators inside it. But It would be great if MTL can support adding custom implementations.

**Comment by Ravenwater** [comment]
MTL can be extended with new matrix types. However, doing so requires deep metaprogramming expertise. I am going to propose this to the principals of MTL as I know they are working on MTL5 which will have tensors and lots of optimizations that are common in the tensor composition environment as meta-programming tricks.

Can you do me a favor? Can you give me the example of the matrix and tensor operator that you encountered for which you need special support? I will take that to the MTL developers and see if they can add your use case to MTL4.
